version: "3"

networks:
  weather-go:
    driver: bridge

services:
  api:
    restart: always
    build: .
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    env_file:
      - .env
      - .env.mysql
    ports:
      - "${PORT_REST}:${PORT_REST}"
    depends_on:
      - "mysql"
    networks:
      - weather-go
  mysql:
    restart: always
    image: mysql:8.0
    env_file:
      - .env.mysql
    volumes:
      - "./db_data:/var/lib/mysql"
    networks:
      - weather-go
  phpmyadmin:
    restart: always
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=8192M
    ports:
      - "8181:80"
    networks:
      - weather-go

