version: "3"

networks:
  pokemon:
    driver: bridge

services:
  front:
    restart: always
    build: ./frontend
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "${PORT_PAGE}:${PORT_PAGE}"
    env_file:
      - .env
    networks:
      - pokemon
  api:
    restart: always
    build: ./backend
    volumes:
      - "./backend:/usr/src/app"
      - "/usr/src/app/node_modules"
    env_file:
      - .env
      - .env.mysql
    ports:
      - "${PORT_REST}:${PORT_REST}"
    depends_on:
      - "mysql"
    networks:
      - pokemon
  mysql:
    restart: always
    image: mariadb:10.5
    env_file:
      - .env.mysql
    volumes:
      - "./db_data:/var/lib/mysql"
    networks:
      - pokemon
  phpmyadmin:
    restart: always
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=8192M
    ports:
      - "8181:80"
    networks:
      - pokemon

