const deleteTable = require('../externalFunc/deleteTable')

exports.seed = function (knex) {
    return deleteTable(knex, ['region_pokemon', 'user_pokemon']).then(() => {
        return deleteTable(knex, ['resistance']).then(() => {
            return knex("resistance").insert([
                { type_A: "Normal", type_B: "Steel", rate: 0.5 },
                { type_A: "Normal", type_B: "Rock", rate: 0.5 },
                { type_A: "Normal", type_B: "Ghost", rate: 0 },

                { type_A: "Fire", type_B: "Fire", rate: 0.5 },
                { type_A: "Fire", type_B: "Rock", rate: 0.5 },
                { type_A: "Fire", type_B: "Water", rate: 0.5 },
                { type_A: "Fire", type_B: "Dragon", rate: 0.5 },
                { type_A: "Fire", type_B: "Grass", rate: 2 },
                { type_A: "Fire", type_B: "Ice", rate: 2 },
                { type_A: "Fire", type_B: "Bug", rate: 2 },
                { type_A: "Fire", type_B: "Steel", rate: 2 },

                { type_A: "Water", type_B: "Water", rate: 0.5 },
                { type_A: "Water", type_B: "Grass", rate: 0.5 },
                { type_A: "Water", type_B: "Dragon", rate: 0.5 },
                { type_A: "Water", type_B: "Ground", rate: 2 },
                { type_A: "Water", type_B: "Fire", rate: 2 },
                { type_A: "Water", type_B: "Rock", rate: 2 },

                { type_A: "Electric", type_B: "Ground", rate: 0 },
                { type_A: "Electric", type_B: "Electric", rate: 0.5 },
                { type_A: "Electric", type_B: "Grass", rate: 0.5 },
                { type_A: "Electric", type_B: "Dragon", rate: 0.5 },
                { type_A: "Electric", type_B: "Flying", rate: 2 },
                { type_A: "Electric", type_B: "Water", rate: 2 },

                { type_A: "Grass", type_B: "Bug", rate: 0.5 },
                { type_A: "Grass", type_B: "Poison", rate: 0.5 },
                { type_A: "Grass", type_B: "Flying", rate: 0.5 },
                { type_A: "Grass", type_B: "Fire", rate: 0.5 },
                { type_A: "Grass", type_B: "Grass", rate: 0.5 },
                { type_A: "Grass", type_B: "Dragon", rate: 0.5 },
                { type_A: "Grass", type_B: "Steel", rate: 0.5 },
                { type_A: "Grass", type_B: "Ground", rate: 2 },
                { type_A: "Grass", type_B: "Water", rate: 2 },
                { type_A: "Grass", type_B: "Rock", rate: 2 },

                { type_A: "Ice", type_B: "Fire", rate: 0.5 },
                { type_A: "Ice", type_B: "Water", rate: 0.5 },
                { type_A: "Ice", type_B: "Ice", rate: 0.5 },
                { type_A: "Ice", type_B: "Steel", rate: 0.5 },
                { type_A: "Ice", type_B: "Flying", rate: 2 },
                { type_A: "Ice", type_B: "Ground", rate: 2 },
                { type_A: "Ice", type_B: "Grass", rate: 2 },
                { type_A: "Ice", type_B: "Dragon", rate: 2 },

                { type_A: "Fighting", type_B: "Ghost", rate: 0 },
                { type_A: "Fighting", type_B: "Bug", rate: 0.5 },
                { type_A: "Fighting", type_B: "Poison", rate: 0.5 },
                { type_A: "Fighting", type_B: "Psychic", rate: 0.5 },
                { type_A: "Fighting", type_B: "Fairy", rate: 0.5 },
                { type_A: "Fighting", type_B: "Flying", rate: 0.5 },
                { type_A: "Fighting", type_B: "Normal", rate: 2 },
                { type_A: "Fighting", type_B: "Steel", rate: 2 },
                { type_A: "Fighting", type_B: "Ice", rate: 2 },
                { type_A: "Fighting", type_B: "Dark", rate: 2 },
                { type_A: "Fighting", type_B: "Rock", rate: 2 },

                { type_A: "Poison", type_B: "Steel", rate: 0 },
                { type_A: "Poison", type_B: "Poison", rate: 0.5 },
                { type_A: "Poison", type_B: "Ground", rate: 0.5 },
                { type_A: "Poison", type_B: "Rock", rate: 0.5 },
                { type_A: "Poison", type_B: "Ghost", rate: 0.5 },
                { type_A: "Poison", type_B: "Grass", rate: 2 },
                { type_A: "Poison", type_B: "Fairy", rate: 2 },

                { type_A: "Ground", type_B: "Flying", rate: 0 },
                { type_A: "Ground", type_B: "Bug", rate: 0.5 },
                { type_A: "Ground", type_B: "Grass", rate: 0.5 },
                { type_A: "Ground", type_B: "Rock", rate: 2 },
                { type_A: "Ground", type_B: "Fire", rate: 2 },
                { type_A: "Ground", type_B: "Poison", rate: 2 },
                { type_A: "Ground", type_B: "Electric", rate: 2 },
                { type_A: "Ground", type_B: "Steel", rate: 2 },

                { type_A: "Flying", type_B: "Electric", rate: 0.5 },
                { type_A: "Flying", type_B: "Rock", rate: 0.5 },
                { type_A: "Flying", type_B: "Steel", rate: 0.5 },
                { type_A: "Flying", type_B: "Bug", rate: 2 },
                { type_A: "Flying", type_B: "Fighting", rate: 2 },
                { type_A: "Flying", type_B: "Grass", rate: 2 },

                { type_A: "Psychic", type_B: "Dark", rate: 0 },
                { type_A: "Psychic", type_B: "Psychic", rate: 0.5 },
                { type_A: "Psychic", type_B: "Steel", rate: 0.5 },
                { type_A: "Psychic", type_B: "Poison", rate: 2 },
                { type_A: "Psychic", type_B: "Fighting", rate: 2 },

                { type_A: "Bug", type_B: "Poison", rate: 0.5 },
                { type_A: "Bug", type_B: "Flying", rate: 0.5 },
                { type_A: "Bug", type_B: "Fighting", rate: 0.5 },
                { type_A: "Bug", type_B: "Fire", rate: 0.5 },
                { type_A: "Bug", type_B: "Ghost", rate: 0.5 },
                { type_A: "Bug", type_B: "Steel", rate: 0.5 },
                { type_A: "Bug", type_B: "Fairy", rate: 0.5 },
                { type_A: "Bug", type_B: "Grass", rate: 2 },
                { type_A: "Bug", type_B: "Psychic", rate: 2 },
                { type_A: "Bug", type_B: "Dark", rate: 2 },

                { type_A: "Rock", type_B: "Ground", rate: 0.5 },
                { type_A: "Rock", type_B: "Fighting", rate: 0.5 },
                { type_A: "Rock", type_B: "Steel", rate: 0.5 },
                { type_A: "Rock", type_B: "Bug", rate: 2 },
                { type_A: "Rock", type_B: "Flying", rate: 2 },
                { type_A: "Rock", type_B: "Fire", rate: 2 },
                { type_A: "Rock", type_B: "Ice", rate: 2 },

                { type_A: "Ghost", type_B: "Normal", rate: 0 },
                { type_A: "Ghost", type_B: "Dark", rate: 0.5 },
                { type_A: "Ghost", type_B: "Psychic", rate: 2 },
                { type_A: "Ghost", type_B: "Ghost", rate: 2 },

                { type_A: "Dragon", type_B: "Fairy", rate: 0 },
                { type_A: "Dragon", type_B: "Steel", rate: 0.5 },
                { type_A: "Dragon", type_B: "Dragon", rate: 2 },

                { type_A: "Dark", type_B: "Fighting", rate: 0.5 },
                { type_A: "Dark", type_B: "Dark", rate: 0.5 },
                { type_A: "Dark", type_B: "Fairy", rate: 0.5 },
                { type_A: "Dark", type_B: "Psychic", rate: 2 },
                { type_A: "Dark", type_B: "Ghost", rate: 2 },

                { type_A: "Steel", type_B: "Water", rate: 0.5 },
                { type_A: "Steel", type_B: "Fire", rate: 0.5 },
                { type_A: "Steel", type_B: "Electric", rate: 0.5 },
                { type_A: "Steel", type_B: "Steel", rate: 0.5 },
                { type_A: "Steel", type_B: "Ice", rate: 2 },
                { type_A: "Steel", type_B: "Rock", rate: 2 },
                { type_A: "Steel", type_B: "Fairy", rate: 2 },

                { type_A: "Fairy", type_B: "Poison", rate: 0.5 },
                { type_A: "Fairy", type_B: "Fire", rate: 0.5 },
                { type_A: "Fairy", type_B: "Steel", rate: 0.5 },
                { type_A: "Fairy", type_B: "Fighting", rate: 2 },
                { type_A: "Fairy", type_B: "Dragon", rate: 2 },
                { type_A: "Fairy", type_B: "Dark", rate: 2 },
            ])
        })
    })
};